#!/bin/bash
echo "Welcome to UBA self service"
echo "Please SLOT IN YOUR CARD"
echo "Please enter your PIN"
read pin
echo "The pin you entered is $pin"
echo "Is that correct"
read answer
echo "Succesfully login"
